name: anatomia_quiz_app
description: Piattaforma d elite di quiz medici e diagnostici con sincronizzazione live da Google Sheets.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

flutter:
  uses-material-design: true
